version: "3"
services:
  bot-web:
    container_name: ${APPLICATION}-web
    build: 
      context: ${DOCKERFILE_DIR}
      args:
        - HOST_PORT=${HOST_PORT}
    ports:
      - "${HOST_PORT}:3000"
    volumes:
      - ${HOST_WORKING_DIR}:/var/run/application