# This is a basic workflow to help you get started with Actions

name: CI-dev-v0.0.1-rc1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ dev-v0.0.1-rc1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ec2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # - working-directory: /home/company/build/web-bot
      # - name: Write path default dir
      #   run: pwd
      #
      - name: What's running?
        working-directory: /home/company/build
        run: echo "Process pull request from $GITHUB_HEAD_REF to $GITHUB_BASE_REF"

      - name: Where is the working dir?
        working-directory: /home/company/build/web-bot
        run: pwd

      - name: Try fetch branchs
        working-directory: /home/company/build/web-bot
        run: git fetch

      - name: Checkout from branch $GITHUB_HEAD_REF
        working-directory: /home/company/build/web-bot
        run: git checkout $GITHUB_HEAD_REF

      - name: Try pull from branch origin/$GITHUB_BASE_REF
        working-directory: /home/company/build/web-bot
        run: git pull origin $GITHUB_BASE_REF

      - name: Run test case on $GITHUB_HEAD_REF
        working-directory: /home/company/build/web-bot
        run: bash mockTest.sh

      - name: Reset code base to $GITHUB_BASE_REF
        if: always()
        working-directory: /home/company/build/web-bot
        run: git checkout $GITHUB_BASE_REF --force
        # uses: actions/checkout@v2-beta
        # with:
        #   repository: 'opencollective/opencollective-frontend'
        #   ref: master
      # - name: Pull new code
      #   working-directory: /home/company/build/web-bot
      #   run: git pull github master

      # - name: Update dependencies
      #   working-directory: /home/company/build/web-bot
      #   run: yarn install

      # - name: Perform test
      #   working-directory: /home/company/build/web-bot
      #   run: yarn test

      # - name: Perform build
      #   working-directory: /home/company/build/web-bot
      #   run: yarn build

      # - name: Write log
      #   working-directory: /home/company/build
      #   run: echo "Pull request from $GITHUB_HEAD_REF to $GITHUB_BASE_REF" >> actions.log

      # - name: clean working dir
      #   if: steps.checkout-matching-branch.outputs.failure === 'true'
      #   uses: actions/checkout@v2-beta
      #   with:
      #     repository: 'opencollective/opencollective-frontend'
      #     ref: master

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
